export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#b7c8e1",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "on-background": "#191c1e",
        "error": "#ba1a1a",
        "surface-dim": "#d8dadc",
        "secondary-container": "#d0e1fb",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "on-secondary": "#ffffff",
        "primary": "#004ac6",
        "tertiary-fixed": "#6ffbbe",
        "background": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#434655",
        "on-surface": "#191c1e",
        "surface-container": "#eceef0",
        "surface": "#f7f9fb",
        "inverse-on-surface": "#eff1f3",
        "outline": "#737686",
        "tertiary": "#006242",
        "surface-bright": "#f7f9fb",
        "on-primary-container": "#eeefff",
        "secondary": "#505f76",
        "on-secondary-container": "#54647a",
        "on-tertiary-fixed": "#002113",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-container": "#bdffdb",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#00174b",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-highest": "#e0e3e5",
        "outline-variant": "#c3c6d7",
        "secondary-fixed": "#d3e4fe",
        "tertiary-container": "#007d55",
        "primary-fixed": "#dbe1ff",
        "surface-container-high": "#e6e8ea",
        "inverse-primary": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-tint": "#0053db",
        "primary-container": "#2563eb",
        "on-primary": "#ffffff",
        "surface-variant": "#e0e3e5",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1440px",
        "sidebar-width": "260px",
        gutter: "1.5rem",
        "margin-mobile": "1rem",
        "stack-sm": "0.5rem",
        "margin-desktop": "2rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "button-text": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-sm": [
          "20px",
          { lineHeight: "28px", fontWeight: "600" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "button-text": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg": [
          "30px",
          { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
